name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for each job
    permissions:
      contents: write # <--- ADD THIS LINE: Grant write permission to the GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          # No caching here, as npm install --force handles clean installs

      - name: Install dependencies (using npm install --force for robustness)
        # This will generate package-lock.json if it doesn't exist and
        # aggressively resolve dependencies, which can help with 'module not found' errors.
        run: npm install --force

      - name: Build React application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          # cname: example.com # Uncomment and replace with your custom domain if you have one
